### ISSUE TITLE
追加予定の機能について ✍️

### ISSUE THREAD

**Issue by baronTommy** [SnO2WMaN/customizable-gitmoji-cli#20]
Hello @SnO2WMaN!

issueではありません 😇  
素晴らしいライブラリですね  

---

私も gitmoji が好きで 最近利用しています  
@SnO2WMaN! の Qiitaなどの記事を見て うんうん と思うところがありました

--- 

私が普段利用している gitmoji 関連など

https://github.com/ngryman/cz-emoji  
これと  

https://github.com/try-react/rr/blob/master/package.json#L75  
このあたりです

package.json に書いているので 
使い勝手がつらいです...

ですので  
`.gitmojirc` に魅力を感じています

---

- 質問のカスタマイズ
- semantic-release との連携 (↓ こんな感じ
  - https://github.com/baron-code-factory/typescript-work-space/blob/master/release.config.js
  - https://github.com/baron-code-factory/typescript-work-space/releases
  - https://github.com/momocow/semantic-release-gitmoji

このような機能があればいいなと思っています   
機能の予定などあれば聞いてみたいです

**Comment by SnO2WMaN** [comment]
現在設定ファイルの部分に色々思うところがありv2を開発していて、
- コミット時のフック
- 設定ファイルの継承
がまだ出来ていませんが、それが終わった後に、バージョン更新の推測とかもやる予定です

**Comment by baronTommy** [comment]
応援しています 🐶
